documents/urls.py
# -*- coding: utf-8 -*-
# Copyright (C) 2018 Nathanael Philipp (jnphilipp) <mail@jnphilipp.org>
#
# This file is part of infohub.
#
# infohub is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# infohub is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with infohub.  If not, see <http://www.gnu.org/licenses/>.

from django.urls import path

from .views import document


app_name = 'documents'
urlpatterns = [
    path('document/', document.ListView.as_view(), name='document_list'),
    path('document/<int:page>/', document.ListView.as_view()),
    path('document/<slug:hash>/', document.DetailView.as_view(),
         name='document_detail'),
]

feeds/urls.py
# -*- coding: utf-8 -*-
# Copyright (C) 2018 Nathanael Philipp (jnphilipp) <mail@jnphilipp.org>
#
# This file is part of infohub.
#
# infohub is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# infohub is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with infohub.  If not, see <http://www.gnu.org/licenses/>.

from django.urls import path

from .views import feed


app_name = 'feeds'
urlpatterns = [
    path('feed/', feed.ListView.as_view(), name='feed_list'),
    path('feed/<int:page>/', feed.ListView.as_view()),
    path('feed/<slug:slug>/', feed.DetailView.as_view(), name='feed_detail'),
    path('feed/<slug:slug>/<slug:hash>', feed.document,
         name='feed_document_detail'),
]

infohub/urls.py
# -*- coding: utf-8 -*-
# Copyright (C) 2018 Nathanael Philipp (jnphilipp) <mail@jnphilipp.org>
#
# This file is part of infohub.
#
# infohub is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# infohub is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with infohub.  If not, see <http://www.gnu.org/licenses/>.

"""infohub URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

from django.contrib import admin
from django.urls import include, path
from django.utils.translation import ugettext_lazy as _
from django.views.generic.base import RedirectView

from . import views

admin.site.site_header = _('infohub administration')


urlpatterns = [
    path('', views.dashboard, name='dashboard'),

    path('admin/', admin.site.urls),
    path('documents/', include('documents.urls')),
    path('feeds/', include('feeds.urls')),
    path('profiles/', include('profiles.urls')),

    path('favicon.ico', RedirectView.as_view(url='/static/images/icon.png')),
]

feeds/models.py
# -*- coding: utf-8 -*-
# Copyright (C) 2018 Nathanael Philipp (jnphilipp) <mail@jnphilipp.org>
#
# This file is part of infohub.
#
# infohub is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# infohub is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with infohub.  If not, see <http://www.gnu.org/licenses/>.

import feedparser
import re
import requests

from django.contrib.contenttypes.fields import GenericRelation
from django.db import models
from django.urls import reverse
from django.template.defaultfilters import slugify
from django.utils.translation import ugettext_lazy as _
from django_fsm import FSMField, transition
from infohub.fields import SingleLineTextField


class Type(models.Model):
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_('Created at')
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name=_('Updated at')
    )
    name = SingleLineTextField(
        unique=True,
        verbose_name=_('Name')
    )

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)
        verbose_name = _('Type')
        verbose_name_plural = _('Types')


class Feed(models.Model):
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_('Created at')
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name=_('Updated at')
    )

    slug = models.SlugField(
        max_length=4096,
        unique=True,
        verbose_name=_('Slug')
    )
    url = models.URLField(
        max_length=2096,
        unique=True,
        verbose_name=_('URL')
    )
    title = SingleLineTextField(
        blank=True,
        null=True,
        verbose_name=_('Title')
    )
    state = FSMField(
        default='alive',
        verbose_name=_('State')
    )
    type = models.ForeignKey(
        Type,
        models.CASCADE,
        related_name='feeds',
        verbose_name=_('Type')
    )

    documents = GenericRelation(
        'documents.Document',
        related_query_name='feeds',
        verbose_name=_('Documents')
    )

    @transition(field=state, source=('alive', 'failed'), target='alive',
                on_error='failed')
    def update(self):
        from documents.models import Document

        if self.type.name == 'RSS':
            rssfeed = feedparser.parse(self.url)
            if self.title != rssfeed.feed.title:
                self.title = rssfeed.feed.title
                self.save()

            for entry in rssfeed.entries:
                url = re.sub(r'#[^#]+$', '', entry.link)
                if not Document.objects.filter(url=url).exists():
                    title = re.sub(r'\s\s+', ' ',
                                   entry.title.replace('\n', ' '))
                    text = requests.get(url).text
                    Document.objects.create(text=text, title=title, url=url,
                                            meta={'source': entry},
                                            content_object=self).hash

    def get_absolute_url(self):
        return reverse('feeds:feed_detail', args=[self.slug])

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.url)
        else:
            orig = Feed.objects.get(pk=self.id)
            if orig.url != self.url:
                self.slug = slugify(self.url)
        super(Feed, self).save(*args, **kwargs)

    def __str__(self):
        return self.title if self.title else self.url

    class Meta:
        ordering = ('state', 'url')
        verbose_name = _('Feed')
        verbose_name_plural = _('Feeds')

feeds/views/feed.py
# -*- coding: utf-8 -*-
# Copyright (C) 2018 Nathanael Philipp (jnphilipp) <mail@jnphilipp.org>
#
# This file is part of infohub.
#
# infohub is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# infohub is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with infohub.  If not, see <http://www.gnu.org/licenses/>.

import json

from django.shortcuts import get_object_or_404, render
from django.utils.decorators import method_decorator
from django.views import generic
from infohub.decorators import piwik

from ..models import Feed


@method_decorator(piwik('Feeds • Feeds • infohub'), name='dispatch')
class ListView(generic.ListView):
    context_object_name = 'feeds'
    model = Feed
    paginate_by = 100

    def get_ordering(self):
        self.order = self.request.GET.get('o', 'url')
        return self.order

    def get_context_data(self, *args, **kwargs):
        context = super(ListView, self).get_context_data(*args, **kwargs)
        context['o'] = self.order
        return context


@method_decorator(piwik('Feed • Feeds • infohub'), name='dispatch')
class DetailView(generic.DetailView):
    model = Feed

    def get_context_data(self, *args, **kwargs):
        context = super(DetailView, self).get_context_data(*args, **kwargs)
        context['do'] = self.request.GET.get('do', '-updated_at')
        context['documents'] = context['feed'].documents. \
            order_by(context['do'])
        return context


@piwik('Document • Feed • Feeds • infohub')
def document(request, slug, hash):
    feed = get_object_or_404(Feed, slug=slug)
    document = get_object_or_404(feed.documents, hash=hash)
    meta_formatted = json.dumps(document.meta, indent=4)
    return render(request, 'feeds/feed_document_detail.html', locals())

feeds/templates/feeds/feed_detail.html
{% extends "infohub/base.html" %}
{% load bootstrap i18n infohub %}


{% block breadcrumbs %}
<li class="breadcrumb-item"><a href="{% url "dashboard" %}">{% trans "Dashboard" %}</a></li>
<li class="breadcrumb-item"><a href="{% url "feeds:feed_list" %}">{% trans "Feeds" %}</a></li>
<li class="breadcrumb-item active" aria-current="page">{{ feed.title|default_if_none:feed.slug }}</li>
{% endblock %}


{% block content %}
<div class="row">
    <div class="col-md">
        <dl class="row">
            <dt class="col-sm-3">{% trans "Title" %}</dt>
            <dd class="col-sm-9">{{ feed.title }}</dd>
            <dt class="col-sm-3">{% trans "URL" %}</dt>
            <dd class="col-sm-9"><a href="{{ feed.url }}">{{ feed.url }}</a></dd>
            <dt class="col-sm-3">{% trans "State" %}</dt>
            <dd class="col-sm-9">{{ feed.state }}</dd>
            <dt class="col-sm-3">{% trans "Type" %}</dt>
            <dd class="col-sm-9">{{ feed.type }}</dd>
        </dl>
    </div>
</div>
<div class="row">
    <div class="col-md">
        <h3 class="text-muted">#{% trans "Documents" %}</h3>
        <hr class="text-muted">
    </div>
</div>
<div class="row">
    <div class="col-md">
        <div class="table-responsive">
            <table class="table table-sm table-hover table-striped">
                <thead>
                    <tr>
                        {% trans "Title" as title_trans %}
                        {% sortable_th column_name=title_trans o=do get_name="do" get_value="title" %}
                        {% trans "URL" as url_trans %}
                        {% sortable_th column_name=url_trans o=do get_name="do" get_value="url" %}
                        {% trans "State" as state_trans %}
                        {% sortable_th column_name=state_trans o=do get_name="do" get_value="state" %}
                        {% trans "Updated at" as updated_at_trans %}
                        {% sortable_th column_name=updated_at_trans o=do get_name="do" get_value="updated_at" %}
                    </tr>
                </thead>
                <tbody>
                    {% for document in documents %}
                        <tr>
                            <th><a href="{% url "feeds:feed_document_detail" feed.slug document.hash %}">{{ document.title|default_if_none:document.hash }}</a></th>
                            <td><a href="{{ document.url }}">{{ document.url }}</a></td>
                            <td>{{ document.state }}</td>
                            <td>{{ document.updated_at|date:"c" }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

feeds/templates/feeds/feed_document_detail.html
{% extends "infohub/base.html" %}
{% load bootstrap i18n infohub %}


{% block breadcrumbs %}
<li class="breadcrumb-item"><a href="{% url "dashboard" %}">{% trans "Dashboard" %}</a></li>
<li class="breadcrumb-item"><a href="{% url "feeds:feed_list" %}">{% trans "Feeds" %}</a></li>
<li class="breadcrumb-item"><a href="{% url "feeds:feed_detail" document.content_object.slug %}">{{ document.content_object.title|default_if_none:document.content_object.slug }}</a></li>
<li class="breadcrumb-item active" aria-current="page">{{ document.title|default_if_none:document.hash }}</li>
{% endblock %}


{% block content %}
<dl class="row">
    <dt class="col-sm-3">{% trans "Created at" %}</dt>
    <dd class="col-sm-9">{{ document.created_at|date:"c" }}</dd>
    <dt class="col-sm-3">{% trans "Updated at" %}</dt>
    <dd class="col-sm-9">{{ document.updated_at|date:"c" }}</dd>
    <dt class="col-sm-3">{% trans "Title" %}</dt>
    <dd class="col-sm-9">{{ document.title }}</dd>
    <dt class="col-sm-3">{% trans "URL" %}</dt>
    <dd class="col-sm-9"><a href="{{ document.url }}">{{ document.url }}</a></dd>
    <dt class="col-sm-3">{% trans "State" %}</dt>
    <dd class="col-sm-9">{{ document.state }}</dd>
    <dt class="col-sm-3">{% trans "Hash" %}</dt>
    <dd class="col-sm-9">{{ document.hash }}</dd>
    <dt class="col-sm-3">{% trans "Related" %}</dt>
        <dd class="col-sm-9">
            <ul>
                {% for doc in document.related.all %}
                    <li><a href="{% url "documents:document_detail" doc.hash %}">{{ doc.title|default_if_none:doc.hash }}</a></li>
                {% endfor %}
            </ul>
        </dd>
    {% if request.user.is_staff %}
        <dt class="col-sm-3">{% trans "Meta" %}</dt>
        <dd class="col-sm-9"><pre>{{ meta_formatted }}</pre></dd>
        <dt class="col-sm-3">{% trans "Text" %}</dt>
        <dd class="col-sm-9">{{ document.text }}</dd>
    {% endif %}
</dl>
{% endblock %}

feeds/templates/feeds/feed_list.html
{% extends "infohub/base.html" %}
{% load bootstrap i18n infohub %}


{% block breadcrumbs %}
<li class="breadcrumb-item"><a href="">{% trans "Dashboard" %}</a></li>
<li class="breadcrumb-item active" aria-current="page">{% trans "Feeds" %}</li>
{% endblock %}


{% block content %}
<div class="row mt-md-1">
    <div class="col-md">
        <div class="table-responsive">
            <table class="table table-sm table-hover table-striped">
                <thead>
                    <tr>
                        {% trans "Title" as title_trans %}
                        {% sortable_th column_name=title_trans o=o get_name="o" get_value="title" %}
                        {% trans "URL" as url_trans %}
                        {% sortable_th column_name=url_trans o=o get_name="o" get_value="url" %}
                        {% trans "State" as state_trans %}
                        {% sortable_th column_name=state_trans o=o get_name="o" get_value="state" %}
                        {% trans "Type" as type_trans %}
                        {% sortable_th column_name=type_trans o=o get_name="o" get_value="type" %}
                        {% trans "#Documents" as nbdocuments_trans %}
                        {% sortable_th column_name=nbdocuments_trans o=o get_name="o" get_value="nbdocuments" %}
                    </tr>
                </thead>
                <tbody>
                    {% for feed in feeds %}
                        <tr>
                            <th><a href="{% url "feeds:feed_detail" feed.slug %}">{{ feed.title|default_if_none:feed.slug }}</a></th>
                            <td><a href="{{ feed.url }}">{{ feed.url }}</a></td>
                            <td>{{ feed.state }}</td>
                            <td>{{ feed.type.name }}</td>
                            <td>{{ feed.documents.count }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% trans "Feeds" as pagination_title %}
        {% url "feeds:feed_list" as base_path %}
        {% pagination paginator page_obj base_path pagination_title o=o %}
    </div>
</div>
{% endblock %}