documents/urls.py
# -*- coding: utf-8 -*-
# Copyright (C) 2018 Nathanael Philipp (jnphilipp) <mail@jnphilipp.org>
#
# This file is part of infohub.
#
# infohub is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# infohub is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with infohub.  If not, see <http://www.gnu.org/licenses/>.

from django.urls import path

from .views import document


app_name = 'documents'
urlpatterns = [
    path('document/', document.ListView.as_view(), name='document_list'),
    path('document/<int:page>/', document.ListView.as_view()),
    path('document/<slug:hash>/', document.DetailView.as_view(),
         name='document_detail'),
]

feeds/urls.py
# -*- coding: utf-8 -*-
# Copyright (C) 2018 Nathanael Philipp (jnphilipp) <mail@jnphilipp.org>
#
# This file is part of infohub.
#
# infohub is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# infohub is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with infohub.  If not, see <http://www.gnu.org/licenses/>.

from django.urls import path

from .views import feed


app_name = 'feeds'
urlpatterns = [
    path('feed/', feed.ListView.as_view(), name='feed_list'),
    path('feed/<int:page>/', feed.ListView.as_view()),
    path('feed/<slug:slug>/', feed.DetailView.as_view(), name='feed_detail'),
    path('feed/<slug:slug>/<slug:hash>', feed.document,
         name='feed_document_detail'),
]

infohub/urls.py
# -*- coding: utf-8 -*-
# Copyright (C) 2018 Nathanael Philipp (jnphilipp) <mail@jnphilipp.org>
#
# This file is part of infohub.
#
# infohub is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# infohub is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with infohub.  If not, see <http://www.gnu.org/licenses/>.

"""infohub URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

from django.contrib import admin
from django.urls import include, path
from django.utils.translation import ugettext_lazy as _
from django.views.generic.base import RedirectView

from . import views

admin.site.site_header = _('infohub administration')


urlpatterns = [
    path('', views.dashboard, name='dashboard'),

    path('admin/', admin.site.urls),
    path('documents/', include('documents.urls')),
    path('feeds/', include('feeds.urls')),
    path('profiles/', include('profiles.urls')),

    path('favicon.ico', RedirectView.as_view(url='/static/images/icon.png')),
]

profiles/urls.py
# -*- coding: utf-8 -*-
# Copyright (C) 2018 Nathanael Philipp (jnphilipp) <mail@jnphilipp.org>
#
# This file is part of infohub.
#
# infohub is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# infohub is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with infohub.  If not, see <http://www.gnu.org/licenses/>.

from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic.base import RedirectView
from infohub.decorators import piwik

from . import views


app_name = 'profiles'
urlpatterns = [
    path('', RedirectView.as_view(pattern_name='profiles:profile'),
         name='index'),
    path('profile/', views.UpdateView.as_view(), name='profile'),

    path('password/',
         piwik('Password change • Profile • infohub')(
            auth_views.PasswordChangeView.as_view(
                success_url='/profiles/password/done/')),
         name='password_change'),
    path('password/done/',
         piwik('Password change • Profile • infohub')(
            auth_views.PasswordChangeDoneView.as_view()),
         name='password_change_done'),


    path('password/reset/',
         piwik('Password reset • Profile • infohub')(
            auth_views.PasswordResetView.as_view(
                success_url='/profiles/password/reset/done/')),
         name='password_reset'),

    path('password/reset/done/',
         piwik('Password reset • Profile • infohub')(
            auth_views.PasswordResetDoneView.as_view()),
         name='password_reset_done'),

    path('password/reset/complete/',
         piwik('Password reset • Profile • infohub')(
            auth_views.PasswordResetCompleteView.as_view()),
         name='password_reset_complete'),

    path('password/reset/confirm/<uidb64>/<token>/',
         piwik('Password reset • Profile • infohub')(
            auth_views.PasswordResetConfirmView.as_view()),
         name='password_reset_confirm'),

    path('signin/', views.signin, name='signin'),
    path('signout/',
         piwik('Sign out • Profile • infohub')(
            auth_views.LogoutView.as_view(
                template_name='registration/signout.html')), name='signout'),
    # path('signup/', views.signup, name='signup'),
]

infohub/views.py
# -*- coding: utf-8 -*-
# Copyright (C) 2018 Nathanael Philipp (jnphilipp) <mail@jnphilipp.org>
#
# This file is part of infohub.
#
# infohub is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# infohub is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with infohub.  If not, see <http://www.gnu.org/licenses/>.

from django.shortcuts import render
from infohub.decorators import piwik


@piwik('Dashboard • infohub')
def dashboard(request):
    return render(request, 'infohub/dashboard.html', locals())

infohub/templates/infohub/base.html
{% load bootstrap i18n static infohub %}
{% get_current_language as LANGUAGE_CODE %}

<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
    <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
        <link rel="shortcut icon" href="{% static "images/icon.png" %}"/>
        {% bootstrap_css %}
        {% bootstrap_js %}
        <link rel="stylesheet" href="{% static "css/infohub.css" %}"/>
        <title>{% block title %}infohub{% endblock %}</title>
        {% block extrahead %}{% endblock %}
        <script type="text/javascript">
            $(document).ready(function() {
                $("#search").autocomplete({
                    source: function(request, response) {
                        $.ajax({
                          url: "",
                          dataType: "json",
                          data: {
                            q: request.term
                          },
                          success: function(data) {
                            var parsed = [];
                            data.results.forEach(function(e) {
                                parsed.push({value: e.text, id: e.id});
                            });

                            response(parsed);
                          }
                        });
                    },
                    select: function(event, ui) {
                        console.log(ui.item.value, ui.item.id);
                        location.href = ui.item.id;
                    },
                    minLength: 2,
                });
            });
        </script>
    </head>
    <body>
        <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="">
                <img alt="Brand" src="{% static "images/icon.png" %}" style="margin-top: -5px; height: 30px; display: inline-block;"/> infohub
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarContent" role="navbar">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        {% url "feeds:feed_list" as feed_list_url %}
                        <a class="nav-link{% if request.path|startswith:feed_list_url %} active{% endif %}" href="{{ feed_list_url }}">
                            {% trans "Feeds" %}
                            {% if request.path|startswith:feed_list_url %}<span class="sr-only">(current)</span>{% endif %}
                        </a>
                    </li>
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            {% url "documents:document_list" as document_list_url %}
                            <a class="nav-link{% if request.path|startswith:document_list_url %} active{% endif %}" href="{{ document_list_url }}">
                                {% trans "Documents" %}
                                {% if request.path|startswith:document_list_url %}<span class="sr-only">(current)</span>{% endif %}
                            </a>
                        </li>
                    {% else %}
                    {% endif %}
                </ul>

                {% if user.is_authenticated %}
                    <form class="form-inline ml-auto my-2 my-lg-0">
                        <input id="search" class="form-control mr-sm-2" type="search" placeholder="{% trans "Search" %}" aria-label="{% trans "Search" %}">
                    </form>
                {% endif %}

                {% if user.is_authenticated %}
                    <ul class="navbar-nav ml-auto">
                        {% url "profiles:index" as profiles_index_url %}
                        <li class="nav-item dropdown{% if request.path|startswith:profiles_index_url %} active{% endif %}">
                            <a class="nav-link dropdown-toggle" href="#" id="profilesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                {% gravatar_img 30 classes="rounded-circle" %}
                                <b>{{ user.get_short_name|default:user.get_username }}</b>
                                {% if request.path|startswith:portfolio_url %}<span class="sr-only">(current)</span>{% endif %}
                            </a>
                            <div class="dropdown-menu" aria-labelledby="profilesDropdown">
                                {% url "profiles:profile" as profiles_profile_url %}
                                <a class="dropdown-item{% if request.path|startswith:profiles_profile_url %} active{% endif %}" href="{{ profiles_profile_url }}">
                                    {% trans "Profile" %}
                                    {% if request.path|startswith:profiles_profile_url %}<span class="sr-only">(current)</span>{% endif %}
                                </a>
                                {% if user.is_staff %}
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="{% url "admin:index" %}">{% trans "Admin" %}</a>
                                {% endif %}
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url "profiles:signout" %}">{% trans "Sign out" %}</a>
                            </ul>
                        </li>
                    </ul>
                {% else %}
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="btn btn-outline-primary" href="{% url "profiles:signin" %}" role="button">{% trans "Sign in" %}</a>
                        </li>
                    </ul>
                {% endif %}
            </div>
        </nav>

        <div class="container-fluid">
            <div class="row">
                <div class="col-md-10 offset-md-1">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            {% block breadcrumbs %}{% endblock %}
                        </ol>
                    </nav>
                    {% messages %}
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    {% block content %}{% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

infohub/templates/infohub/dashboard.html
{% extends "infohub/base.html" %}
{% load i18n %}


{% block breadcrumbs %}
<li class="active">{% trans "Dashboard" %}</li>
{% endblock %}


{% block content %}
{% endblock %}